### ISSUE TITLE
yaml codeblock throws errors

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8738]
-> Take a look at the currently used syntax-highlighting-Plugin

**Comment by angelobanse** [comment]
Text between `{{` and `}}` is being interpreted by jinja2 as a template element - despite being in a code-block.

Solution: use the `{% raw %}` `{% endraw %}` tags around the code, to disable interpretation.
e.g.

        ```yml
        {% raw %}
            - name: Uploading artifacts (SUMO binaries)
              uses: actions/upload-artifact@v1
              with:
                name: Linux-${{ matrix.compiler }}-${{ matrix.build_type }}
                path: sumo/bin
        {% endraw %}
        ```
